import re
import os

strings_en = {
    "app_name": "ONE SHIFT",
    "empty": "",
    "exit_game_dialog_title": "Exit Game?",
    "exit_game_dialog_text": "Your progress and settings are saved automatically.",
    "yes_exit": "YES, EXIT",
    "return_to_menu": "RETURN TO MENU",
    "new_game_dialog_title": "Start a new game?",
    "new_game_dialog_text": "Unlocked levels, stars, and records will be deleted. Settings and purchases will be kept.",
    "start_new_game": "START NEW GAME",
    "cancel": "CANCEL",
    "continue_game": "CONTINUE",
    "new_game": "NEW GAME",
    "select_level": "SELECT LEVEL",
    "ads_removed": "ADS REMOVED ✓",
    "remove_ads": "REMOVE ADS",
    "settings_upper": "SETTINGS",
    "about_game": "ABOUT GAME",
    "exit_game": "EXIT GAME",
    "back": "Back",
    "level_locked": "🔒",
    "audio": "AUDIO",
    "music_volume": "MUSIC: %1$d%%",
    "sfx_volume": "SOUND EFFECTS: %1$d%%",
    "purchases": "PURCHASES",
    "auto_ads_removed": "Automatic ads are removed ✓",
    "restore_purchase": "Restore purchase",
    "save_and_back": "SAVE AND BACK TO MENU",
    "restore_defaults": "RESTORE DEFAULTS",
    "about_title": "About",
    "about_description": "A logic puzzle based on movement, observation, and thinking.",
    "how_to_play": "HOW TO PLAY",
    "how_to_play_text": "Swipe the rows and columns to reconstruct the displayed pattern. Pieces that exit one edge reappear on the opposite side.",
    "objective": "OBJECTIVE",
    "objective_text": "Solve each level in as few moves as possible and get up to five stars.",
    "master_each_level": "MASTER EACH LEVEL",
    "master_each_level_text": "You can replay any unlocked level to improve your record and number of stars.",
    "version_text": "Version 1.0",
    "created_in_romania": "Created in Romania",
    "back_to_menu": "BACK TO MENU",
    "moves_used": "Moves used: %1$d",
    "recommended_moves": "Recommended moves: %1$d",
    "best_score": "Best result: %1$d",
    "next_level": "NEXT LEVEL",
    "replay_level": "REPLAY LEVEL",
    "main_menu": "MAIN MENU",
    "success": "Success",
    "error": "Error",
    "ok": "OK",
    "price_text": "Price: %1$s",
    "buy": "BUY",
    "reset": "Reset",
    "hint_button": "HINT...",
    "loading": "LOADING...",
    "are_you_sure": "Are you sure?",
    "are_you_sure_text": "You will lose the moves made in this attempt. Completed levels, stars, and records remain saved.",
    "return_to_game": "RETURN TO GAME",
    "congratulations": "Congratulations",
    "level_text": "Level %1$d",
    "moves_text": "Moves: %1$d",
    "model": "Model",
    "free_hint": "Free Hint",
    "watch_video_hint": "Watch Video - +1 Hint",
    "swipe_to_recreate": "Swipe to recreate the pattern",
    "daily_hints_text": "%1$d daily hints",
    "bonus_hints_text": "%1$d bonus hints"
}

strings_ro = {
    "app_name": "ONE SHIFT",
    "empty": "",
    "exit_game_dialog_title": "Ieși din joc?",
    "exit_game_dialog_text": "Progresul și setările tale sunt salvate automat.",
    "yes_exit": "DA, IEȘI",
    "return_to_menu": "REVINO LA MENIU",
    "new_game_dialog_title": "Începi un joc nou?",
    "new_game_dialog_text": "Nivelurile deblocate, stelele și recordurile vor fi șterse. Setările și achizițiile vor fi păstrate.",
    "start_new_game": "ÎNCEPE JOC NOU",
    "cancel": "ANULEAZĂ",
    "continue_game": "CONTINUĂ",
    "new_game": "JOC NOU",
    "select_level": "SELECTEAZĂ NIVELUL",
    "ads_removed": "RECLAME ELIMINATE ✓",
    "remove_ads": "ELIMINĂ RECLAMELE",
    "settings_upper": "SETĂRI",
    "about_game": "DESPRE JOC",
    "exit_game": "IEȘIRE DIN JOC",
    "back": "Înapoi",
    "level_locked": "🔒",
    "audio": "AUDIO",
    "music_volume": "MUZICĂ: %1$d%%",
    "sfx_volume": "EFECTE SONORE: %1$d%%",
    "purchases": "ACHIZIȚII",
    "auto_ads_removed": "Reclamele automate sunt eliminate ✓",
    "restore_purchase": "Restaurează achiziția",
    "save_and_back": "SALVEAZĂ ȘI ÎNAPOI LA MENIU",
    "restore_defaults": "RESTAUREAZĂ VALORILE IMPLICITE",
    "about_title": "Despre",
    "about_description": "Un puzzle de logică bazat pe mișcare, observație și gândire.",
    "how_to_play": "CUM SE JOACĂ",
    "how_to_play_text": "Glisează rândurile și coloanele pentru a reconstrui modelul afișat. Piesele care ies printr-o margine reapar prin partea opusă.",
    "objective": "OBIECTIV",
    "objective_text": "Rezolvă fiecare nivel în cât mai puține mutări și obține până la cinci stele.",
    "master_each_level": "STĂPÂNEȘTE FIECARE NIVEL",
    "master_each_level_text": "Poți rejuca orice nivel deblocat pentru a-ți îmbunătăți recordul și numărul de stele.",
    "version_text": "Versiunea 1.0",
    "created_in_romania": "Creat în România",
    "back_to_menu": "ÎNAPOI LA MENIU",
    "moves_used": "Mutări folosite: %1$d",
    "recommended_moves": "Mutări recomandate: %1$d",
    "best_score": "Cel mai bun rezultat: %1$d",
    "next_level": "NIVELUL URMĂTOR",
    "replay_level": "REIA NIVELUL",
    "main_menu": "MENIU PRINCIPAL",
    "success": "Succes",
    "error": "Eroare",
    "ok": "OK",
    "price_text": "Preț: %1$s",
    "buy": "CUMPĂRĂ",
    "reset": "Reset",
    "hint_button": "INDICIU...",
    "loading": "SE ÎNCARCĂ...",
    "are_you_sure": "Ești sigur?",
    "are_you_sure_text": "Vei pierde mutările făcute în această încercare. Nivelurile terminate, stelele și recordurile rămân salvate.",
    "return_to_game": "REVENIRE ÎN JOC",
    "congratulations": "Felicitări",
    "level_text": "Nivel %1$d",
    "moves_text": "Mutări: %1$d",
    "model": "Model",
    "free_hint": "Indiciu Gratuit",
    "watch_video_hint": "Urmărește Video - +1 Indiciu",
    "swipe_to_recreate": "Glisează pentru a recrea modelul",
    "daily_hints_text": "%1$d indicii zilnice",
    "bonus_hints_text": "%1$d indicii bonus"
}

strings_es = {
    "app_name": "ONE SHIFT",
    "empty": "",
    "exit_game_dialog_title": "¿Salir del juego?",
    "exit_game_dialog_text": "Tu progreso y configuración se guardan automáticamente.",
    "yes_exit": "SÍ, SALIR",
    "return_to_menu": "VOLVER AL MENÚ",
    "new_game_dialog_title": "¿Empezar un juego nuevo?",
    "new_game_dialog_text": "Los niveles desbloqueados, estrellas y récords serán eliminados. Se conservarán los ajustes y compras.",
    "start_new_game": "EMPEZAR JUEGO NUEVO",
    "cancel": "CANCELAR",
    "continue_game": "CONTINUAR",
    "new_game": "JUEGO NUEVO",
    "select_level": "SELECCIONAR NIVEL",
    "ads_removed": "ANUNCIOS ELIMINADOS ✓",
    "remove_ads": "ELIMINAR ANUNCIOS",
    "settings_upper": "CONFIGURACIÓN",
    "about_game": "SOBRE EL JUEGO",
    "exit_game": "SALIR DEL JUEGO",
    "back": "Atrás",
    "level_locked": "🔒",
    "audio": "AUDIO",
    "music_volume": "MÚSICA: %1$d%%",
    "sfx_volume": "EFECTOS DE SONIDO: %1$d%%",
    "purchases": "COMPRAS",
    "auto_ads_removed": "Los anuncios automáticos están eliminados ✓",
    "restore_purchase": "Restaurar compra",
    "save_and_back": "GUARDAR Y VOLVER AL MENÚ",
    "restore_defaults": "RESTAURAR VALORES PREDETERMINADOS",
    "about_title": "Acerca de",
    "about_description": "Un rompecabezas lógico basado en movimiento, observación y pensamiento.",
    "how_to_play": "CÓMO JUGAR",
    "how_to_play_text": "Desliza las filas y columnas para reconstruir el patrón mostrado. Las piezas que salen por un borde reaparecen por el lado opuesto.",
    "objective": "OBJETIVO",
    "objective_text": "Resuelve cada nivel en la menor cantidad de movimientos posible y consigue hasta cinco estrellas.",
    "master_each_level": "DOMINA CADA NIVEL",
    "master_each_level_text": "Puedes volver a jugar cualquier nivel desbloqueado para mejorar tu récord y número de estrellas.",
    "version_text": "Versión 1.0",
    "created_in_romania": "Creado en Rumania",
    "back_to_menu": "VOLVER AL MENÚ",
    "moves_used": "Movimientos usados: %1$d",
    "recommended_moves": "Movimientos recomendados: %1$d",
    "best_score": "Mejor resultado: %1$d",
    "next_level": "SIGUIENTE NIVEL",
    "replay_level": "REPETIR NIVEL",
    "main_menu": "MENÚ PRINCIPAL",
    "success": "Éxito",
    "error": "Error",
    "ok": "OK",
    "price_text": "Precio: %1$s",
    "buy": "COMPRAR",
    "reset": "Reiniciar",
    "hint_button": "PISTA...",
    "loading": "CARGANDO...",
    "are_you_sure": "¿Estás seguro?",
    "are_you_sure_text": "Perderás los movimientos realizados en este intento. Los niveles completados, estrellas y récords se mantienen guardados.",
    "return_to_game": "VOLVER AL JUEGO",
    "congratulations": "¡Felicidades!",
    "level_text": "Nivel %1$d",
    "moves_text": "Movimientos: %1$d",
    "model": "Modelo",
    "free_hint": "Pista Gratis",
    "watch_video_hint": "Ver Video - +1 Pista",
    "swipe_to_recreate": "Desliza para recrear el patrón",
    "daily_hints_text": "%1$d pistas diarias",
    "bonus_hints_text": "%1$d pistas extra"
}

strings_it = {
    "app_name": "ONE SHIFT",
    "empty": "",
    "exit_game_dialog_title": "Uscire dal gioco?",
    "exit_game_dialog_text": "I tuoi progressi e le impostazioni vengono salvati automaticamente.",
    "yes_exit": "SÌ, ESCI",
    "return_to_menu": "TORNA AL MENU",
    "new_game_dialog_title": "Iniziare un nuovo gioco?",
    "new_game_dialog_text": "I livelli sbloccati, le stelle e i record verranno eliminati. Impostazioni e acquisti verranno mantenuti.",
    "start_new_game": "INIZIA NUOVO GIOCO",
    "cancel": "ANNULLA",
    "continue_game": "CONTINUA",
    "new_game": "NUOVO GIOCO",
    "select_level": "SELEZIONA LIVELLO",
    "ads_removed": "ANNUNCI RIMOSSI ✓",
    "remove_ads": "RIMUOVI ANNUNCI",
    "settings_upper": "IMPOSTAZIONI",
    "about_game": "SUL GIOCO",
    "exit_game": "ESCI DAL GIOCO",
    "back": "Indietro",
    "level_locked": "🔒",
    "audio": "AUDIO",
    "music_volume": "MUSICA: %1$d%%",
    "sfx_volume": "EFFETTI SONORI: %1$d%%",
    "purchases": "ACQUISTI",
    "auto_ads_removed": "Gli annunci automatici sono rimossi ✓",
    "restore_purchase": "Ripristina acquisto",
    "save_and_back": "SALVA E TORNA AL MENU",
    "restore_defaults": "RIPRISTINA PREDEFINITI",
    "about_title": "Info",
    "about_description": "Un puzzle logico basato su movimento, osservazione e pensiero.",
    "how_to_play": "COME GIOCARE",
    "how_to_play_text": "Scorri le righe e le colonne per ricostruire il modello visualizzato. I pezzi che escono da un bordo riappaiono dal lato opposto.",
    "objective": "OBIETTIVO",
    "objective_text": "Risolvi ogni livello nel minor numero di mosse possibile e ottieni fino a cinque stelle.",
    "master_each_level": "PADRONEGGIA OGNI LIVELLO",
    "master_each_level_text": "Puoi rigiocare qualsiasi livello sbloccato per migliorare il tuo record e il numero di stelle.",
    "version_text": "Versione 1.0",
    "created_in_romania": "Creato in Romania",
    "back_to_menu": "TORNA AL MENU",
    "moves_used": "Mosse usate: %1$d",
    "recommended_moves": "Mosse consigliate: %1$d",
    "best_score": "Miglior risultato: %1$d",
    "next_level": "PROSSIMO LIVELLO",
    "replay_level": "RIGIOCA LIVELLO",
    "main_menu": "MENU PRINCIPALE",
    "success": "Successo",
    "error": "Errore",
    "ok": "OK",
    "price_text": "Prezzo: %1$s",
    "buy": "ACQUISTA",
    "reset": "Reset",
    "hint_button": "SUGGERIMENTO...",
    "loading": "CARICAMENTO...",
    "are_you_sure": "Sei sicuro?",
    "are_you_sure_text": "Perderai le mosse fatte in questo tentativo. I livelli completati, le stelle e i record rimangono salvati.",
    "return_to_game": "TORNA AL GIOCO",
    "congratulations": "Congratulazioni!",
    "level_text": "Livello %1$d",
    "moves_text": "Mosse: %1$d",
    "model": "Modello",
    "free_hint": "Suggerimento Gratis",
    "watch_video_hint": "Guarda Video - +1 Sugger.",
    "swipe_to_recreate": "Scorri per ricreare il modello",
    "daily_hints_text": "%1$d suggerimenti giornalieri",
    "bonus_hints_text": "%1$d suggerimenti bonus"
}

def generate_xml(strings_dict, file_path):
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, "w") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n')
        f.write('<resources>\n')
        for k, v in strings_dict.items():
            escaped_v = v.replace("'", "\\'").replace("&", "&amp;")
            f.write(f'    <string name="{k}">{escaped_v}</string>\n')
        f.write('</resources>\n')

generate_xml(strings_en, "app/src/main/res/values/strings.xml")
generate_xml(strings_ro, "app/src/main/res/values-ro/strings.xml")
generate_xml(strings_es, "app/src/main/res/values-es/strings.xml")
generate_xml(strings_it, "app/src/main/res/values-it/strings.xml")

with open("app/src/main/java/com/example/MainActivity.kt", "r") as f:
    text = f.read()

replacements = {
    'Text("Ieși din joc?"': 'Text(stringResource(R.string.exit_game_dialog_title)',
    'Text("Progresul și setările tale sunt salvate automat."': 'Text(stringResource(R.string.exit_game_dialog_text)',
    'Text("DA, IEȘI"': 'Text(stringResource(R.string.yes_exit)',
    'Text("REVINO LA MENIU"': 'Text(stringResource(R.string.return_to_menu)',
    'Text("Începi un joc nou?"': 'Text(stringResource(R.string.new_game_dialog_title)',
    'Text("Nivelurile deblocate, stelele și recordurile vor fi șterse. Setările și achizițiile vor fi păstrate."': 'Text(stringResource(R.string.new_game_dialog_text)',
    'Text("ÎNCEPE JOC NOU"': 'Text(stringResource(R.string.start_new_game)',
    'Text("ANULEAZĂ"': 'Text(stringResource(R.string.cancel)',
    'Text("CONTINUĂ"': 'Text(stringResource(R.string.continue_game)',
    'Text("JOC NOU"': 'Text(stringResource(R.string.new_game)',
    'Text("SELECTEAZĂ NIVELUL"': 'Text(stringResource(R.string.select_level)',
    'Text("RECLAME ELIMINATE ✓"': 'Text(stringResource(R.string.ads_removed)',
    'Text("ELIMINĂ RECLAMELE"': 'Text(stringResource(R.string.remove_ads)',
    'Text("SETĂRI"': 'Text(stringResource(R.string.settings_upper)',
    'Text("DESPRE JOC"': 'Text(stringResource(R.string.about_game)',
    'Text("IEȘIRE DIN JOC"': 'Text(stringResource(R.string.exit_game)',
    'Text("Înapoi"': 'Text(stringResource(R.string.back)',
    'Text("Selectează nivelul"': 'Text(stringResource(R.string.select_level)',
    'Text("🔒"': 'Text(stringResource(R.string.level_locked)',
    'Text("AUDIO"': 'Text(stringResource(R.string.audio)',
    'Text("ACHIZIȚII"': 'Text(stringResource(R.string.purchases)',
    'Text("Reclamele automate sunt eliminate ✓"': 'Text(stringResource(R.string.auto_ads_removed)',
    'Text("Elimină reclamele"': 'Text(stringResource(R.string.remove_ads)',
    'Text("Restaurează achiziția"': 'Text(stringResource(R.string.restore_purchase)',
    'Text("SALVEAZĂ ȘI ÎNAPOI LA MENIU"': 'Text(stringResource(R.string.save_and_back)',
    'Text("RESTAUREAZĂ VALORILE IMPLICITE"': 'Text(stringResource(R.string.restore_defaults)',
    'Text("Despre"': 'Text(stringResource(R.string.about_title)',
    'Text("Un puzzle de logică bazat pe mișcare, observație și gândire."': 'Text(stringResource(R.string.about_description)',
    'Text("CUM SE JOACĂ"': 'Text(stringResource(R.string.how_to_play)',
    'Text("Glisează rândurile și coloanele pentru a reconstrui modelul afișat. Piesele care ies printr-o margine reapar prin partea opusă."': 'Text(stringResource(R.string.how_to_play_text)',
    'Text("OBIECTIV"': 'Text(stringResource(R.string.objective)',
    'Text("Rezolvă fiecare nivel în cât mai puține mutări și obține până la cinci stele."': 'Text(stringResource(R.string.objective_text)',
    'Text("STĂPÂNEȘTE FIECARE NIVEL"': 'Text(stringResource(R.string.master_each_level)',
    'Text("Poți rejuca orice nivel deblocat pentru a-ți îmbunătăți recordul și numărul de stele."': 'Text(stringResource(R.string.master_each_level_text)',
    'Text("Versiunea 1.0"': 'Text(stringResource(R.string.version_text)',
    'Text("Creat în România"': 'Text(stringResource(R.string.created_in_romania)',
    'Text("ÎNAPOI LA MENIU"': 'Text(stringResource(R.string.back_to_menu)',
    'Text("NIVELUL URMĂTOR"': 'Text(stringResource(R.string.next_level)',
    'Text("REIA NIVELUL"': 'Text(stringResource(R.string.replay_level)',
    'Text("MENIU PRINCIPAL"': 'Text(stringResource(R.string.main_menu)',
    'Text("Succes"': 'Text(stringResource(R.string.success)',
    'Text("Eroare"': 'Text(stringResource(R.string.error)',
    'Text("OK"': 'Text(stringResource(R.string.ok)',
    'Text("CUMPĂRĂ"': 'Text(stringResource(R.string.buy)',
    'Text("IEȘIRE JOC"': 'Text(stringResource(R.string.exit_game)',
    'Text("Reset"': 'Text(stringResource(R.string.reset)',
    'Text("INDICIU..."': 'Text(stringResource(R.string.hint_button)',
    'Text("SE ÎNCARCĂ..."': 'Text(stringResource(R.string.loading)',
    'Text("Ești sigur?"': 'Text(stringResource(R.string.are_you_sure)',
    'Text("Vei pierde mutările făcute în această încercare. Nivelurile terminate, stelele și recordurile rămân salvate."': 'Text(stringResource(R.string.are_you_sure_text)',
    'Text("REVENIRE ÎN JOC"': 'Text(stringResource(R.string.return_to_game)',
    'Text("Felicitări"': 'Text(stringResource(R.string.congratulations)',
    'Text("Indiciu Gratuit"': 'Text(stringResource(R.string.free_hint)',
    'Text("Urmărește Video - +1 Indiciu"': 'Text(stringResource(R.string.watch_video_hint)',
    'Text("Model"': 'Text(stringResource(R.string.model)',
    
    # Dynamic ones
    'Text("MUZICĂ: ${(musicVolume * 100).toInt()}%"': 'Text(stringResource(R.string.music_volume, (musicVolume * 100).toInt())',
    'Text("EFECTE SONORE: ${(sfxVolume * 100).toInt()}%"': 'Text(stringResource(R.string.sfx_volume, (sfxVolume * 100).toInt())',
    'Text("Mutări folosite: $movesUsed"': 'Text(stringResource(R.string.moves_used, movesUsed)',
    'Text("Mutări recomandate: $recommendedMoves"': 'Text(stringResource(R.string.recommended_moves, recommendedMoves)',
    'Text("Cel mai bun rezultat: $bestMoves"': 'Text(stringResource(R.string.best_score, bestMoves)',
    'Text("Preț: ${state.price}"': 'Text(stringResource(R.string.price_text, state.price))',
}

for k, v in replacements.items():
    text = text.replace(k, v)

# For "Nivel $currentLevel"
text = text.replace('Text("Nivel $currentLevel", color = Color(0xFFD0BCFF), fontSize = 20.sp, fontWeight = FontWeight.Bold)',
                    'Text(stringResource(R.string.level_text, currentLevel), color = Color(0xFFD0BCFF), fontSize = 20.sp, fontWeight = FontWeight.Bold)')

# For "Mutări: $moveCount"
text = text.replace('Text("Mutări: $moveCount", color = Color(0xFFD0BCFF), fontSize = 20.sp, fontWeight = FontWeight.Bold)',
                    'Text(stringResource(R.string.moves_text, moveCount), color = Color(0xFFD0BCFF), fontSize = 20.sp, fontWeight = FontWeight.Bold)')

# Also wait, the string for "Nivel $currentLevel" could be different. Let's make sure it handles any case.
text = re.sub(r'Text\("Nivel \$([a-zA-Z0-9_]+)"', r'Text(stringResource(R.string.level_text, \1)', text)
text = re.sub(r'Text\("Mutări: \$([a-zA-Z0-9_]+)"', r'Text(stringResource(R.string.moves_text, \1)', text)
text = re.sub(r'Text\("\$([a-zA-Z0-9_]+) indicii zilnice"', r'Text(stringResource(R.string.daily_hints_text, \1)', text)
text = re.sub(r'Text\("\$([a-zA-Z0-9_]+) indicii bonus"', r'Text(stringResource(R.string.bonus_hints_text, \1)', text)

# There is also "Felicitări!" or just "Felicitări"
text = text.replace('Text("Felicitări!"', 'Text(stringResource(R.string.congratulations)')
text = text.replace('Text("Model"', 'Text(stringResource(R.string.model)')

# Check if there is missing imports
if "import androidx.compose.ui.res.stringResource" not in text:
    text = text.replace("import androidx.compose.ui.Modifier", "import androidx.compose.ui.res.stringResource\nimport androidx.compose.ui.Modifier")

with open("app/src/main/java/com/example/MainActivity.kt", "w") as f:
    f.write(text)

